### ISSUE TITLE
Binder Example Gallery Failure

### ISSUE THREAD

**Issue by Strangemother** [AeroPython/PyFME#90] opened 2016-11-07 13:12 UTC
The example site does not build

http://mybinder.org/repo/AeroPython/PyFME

After roughly 1 minute the interface displays 'failure'

The browser is successfully making requests. The first 60~ requests:

`{"id":"80c376f577cb638e311ce41440af2f21","template-name":"aeropython-pyfme","location":null,"status":"deploying"}`

Followed by a failure response:

`{"id":"b6736adf65897e3cf7e6c241b9e50348","template-name":"aeropython-pyfme","location":null,"status":"failed"}`

**Comment by Juanlu001** [comment] 2016-11-07 13:13
@Strangemother Apparently there are some problems with mybinder:

**Comment by salgozino** [comment] 2016-11-08 14:06
Mybinder is running now, and the example gallery open the Notebook. The problem now is the links to the examples. That links gives an 404 error. You change the adress to the files or something?

**Comment by aeroaks** [comment] 2016-11-08 14:12
it has the same error as the one fixed in #90 . I do not know how mybinder works! do we need to push the changes?

**Comment by Juanlu001** [comment] 2016-11-08 14:53
I just tried http://mybinder.org/repo/aeropython/pyfme and the index.ipynb and its links work as expected, after @aeroaks fixed them. Would you please try again?

**Comment by aeroaks** [comment] 2016-11-08 14:56
It works for me as well! If confirmed by other members, we can close the issue?

**Comment by Juanlu001** [comment] 2016-11-08 15:13
If someone cares to revert 58708c69, we can close it right now :)

**Comment by aqreed** [comment] 2016-11-08 15:13
it is still using the old examples (Cessna 310)...

**Comment by Juanlu001** [comment] 2016-11-08 15:16
The current link shows a static version using nbviewer, still outdated. These are two separate issues: one involves changing one line, the other exporting all the scripts again. If someone does both, great! Otherwise I don't see a reason not to restore the link to mybinder, now that it's working.

**Comment by Juanlu001** [comment] 2016-11-08 16:23
Closed in #94!

**Closed by Juanlu001** 2016-11-08 16:23 UTC
Labels: easy
